/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetNewsParams,
  NewsCreateDTO,
  NewsResponseDTO
} from '../model';

import { customFetch } from '../../utils/fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getGetNewsUrl = (params?: GetNewsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/news?${stringifiedParams}` : `/api/news`
}

export const getNews = async (params?: GetNewsParams, options?: RequestInit): Promise<NewsResponseDTO[]> => {
  
  return customFetch<NewsResponseDTO[]>(getGetNewsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getGetNewsQueryKey = (params?: GetNewsParams,) => {
    return [
    `/api/news`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetNewsQueryOptions = <TData = Awaited<ReturnType<typeof getNews>>, TError = void>(params?: GetNewsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNews>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetNewsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getNews>>> = ({ signal }) => getNews(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   retry: false, refetchOnReconnect: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getNews>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetNewsQueryResult = NonNullable<Awaited<ReturnType<typeof getNews>>>
export type GetNewsQueryError = void


export function useGetNews<TData = Awaited<ReturnType<typeof getNews>>, TError = void>(
 params: undefined |  GetNewsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNews>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNews>>,
          TError,
          Awaited<ReturnType<typeof getNews>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNews<TData = Awaited<ReturnType<typeof getNews>>, TError = void>(
 params?: GetNewsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNews>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNews>>,
          TError,
          Awaited<ReturnType<typeof getNews>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNews<TData = Awaited<ReturnType<typeof getNews>>, TError = void>(
 params?: GetNewsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNews>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetNews<TData = Awaited<ReturnType<typeof getNews>>, TError = void>(
 params?: GetNewsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNews>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetNewsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getUpdateNewsUrl = () => {


  

  return `/api/news`
}

export const updateNews = async (newsCreateDTO: NewsCreateDTO, options?: RequestInit): Promise<NewsResponseDTO> => {
  
  return customFetch<NewsResponseDTO>(getUpdateNewsUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      newsCreateDTO,)
  }
);}
  



export const getUpdateNewsMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateNews>>, TError,{data: NewsCreateDTO}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateNews>>, TError,{data: NewsCreateDTO}, TContext> => {

const mutationKey = ['updateNews'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateNews>>, {data: NewsCreateDTO}> = (props) => {
          const {data} = props ?? {};

          return  updateNews(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateNewsMutationResult = NonNullable<Awaited<ReturnType<typeof updateNews>>>
    export type UpdateNewsMutationBody = NewsCreateDTO
    export type UpdateNewsMutationError = void

    export const useUpdateNews = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateNews>>, TError,{data: NewsCreateDTO}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateNews>>,
        TError,
        {data: NewsCreateDTO},
        TContext
      > => {
      return useMutation(getUpdateNewsMutationOptions(options), queryClient);
    }
    export const getAddNewsUrl = () => {


  

  return `/api/news`
}

export const addNews = async (newsCreateDTO: NewsCreateDTO, options?: RequestInit): Promise<NewsResponseDTO> => {
  
  return customFetch<NewsResponseDTO>(getAddNewsUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      newsCreateDTO,)
  }
);}
  



export const getAddNewsMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addNews>>, TError,{data: NewsCreateDTO}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof addNews>>, TError,{data: NewsCreateDTO}, TContext> => {

const mutationKey = ['addNews'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addNews>>, {data: NewsCreateDTO}> = (props) => {
          const {data} = props ?? {};

          return  addNews(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AddNewsMutationResult = NonNullable<Awaited<ReturnType<typeof addNews>>>
    export type AddNewsMutationBody = NewsCreateDTO
    export type AddNewsMutationError = void

    export const useAddNews = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addNews>>, TError,{data: NewsCreateDTO}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addNews>>,
        TError,
        {data: NewsCreateDTO},
        TContext
      > => {
      return useMutation(getAddNewsMutationOptions(options), queryClient);
    }
    export const getDeleteNewsUrl = () => {


  

  return `/api/news`
}

export const deleteNews = async ( options?: RequestInit): Promise<void> => {
  
  return customFetch<void>(getDeleteNewsUrl(),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  



export const getDeleteNewsMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteNews>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteNews>>, TError,void, TContext> => {

const mutationKey = ['deleteNews'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteNews>>, void> = () => {
          

          return  deleteNews(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteNewsMutationResult = NonNullable<Awaited<ReturnType<typeof deleteNews>>>
    
    export type DeleteNewsMutationError = void

    export const useDeleteNews = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteNews>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteNews>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getDeleteNewsMutationOptions(options), queryClient);
    }
    