spring.application.name=kletterapp

# Where the database is running
# Datasource serves as the connection point to the PostgreSQL database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
# Driver class helps Spring Boot to know which connection class to use for the database connection
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate settings
# Hibernate is a library that helps with the interaction between Java applications and relational databases.
# It provides an Object-Relational Mapping (ORM) framework, allowing developers to work with databases using 
# Java objects instead of SQL queries.

# Determines how the schema is created or updated
# Hibernate compares your entity classes to the actual schema in the database. If something is missing or
# out of sync, it updates the tables to match your Java definitions.
# Don't do that in production, because it can lead to data loss if not used carefully. In development, it can be useful to
# automatically create or update the database schema based on your entity classes.
spring.jpa.hibernate.ddl-auto=validate
# See SQL statements in the console
spring.jpa.show-sql=true
# tells Hibernate which SQL dialect to use when generating SQL queries for the database (use PostgreSQL in this case) deprecated?
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# This setting allows Hibernate to keep the database connection open during the entire request processing, 
# which can be useful for lazy loading of entities. However, it can also lead to performance issues if not 
# used carefully, as it may keep connections open longer than necessary.
spring.jpa.open-in-view=true

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.dachpc.kletterapp=DEBUG

spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_JWK_SET_URI}

app.upload.dir=uploads