# ==============================
# Stage 1: Build the application
# ==============================

FROM maven:3.9-eclipse-temurin-25 AS builder

WORKDIR /app

COPY kletterapp/pom.xml ./

RUN mvn dependency:go-offline

COPY kletterapp/src ./src

RUN mvn clean package -DskipTests


# ============================
# Stage 2: Run the application
# ============================

FROM eclipse-temurin:25-jre AS runner

WORKDIR /app

COPY --from=builder /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]

