/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  Kommentar
} from '../model';


export const getGetKommentareByRouteIDResponseMock = (): Kommentar[] => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.number.int(), routenId: faker.number.int(), userId: faker.string.alpha({length: {min: 10, max: 20}}), datum: faker.date.past().toISOString().slice(0, 19) + 'Z', text: faker.string.alpha({length: {min: 10, max: 20}})})))

export const getAddKommentarResponseMock = (overrideResponse: Partial<Extract<Kommentar, object>> = {}): Kommentar => ({id: faker.number.int(), routenId: faker.number.int(), userId: faker.string.alpha({length: {min: 10, max: 20}}), datum: faker.date.past().toISOString().slice(0, 19) + 'Z', text: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getUpdateKommentarResponseMock = (overrideResponse: Partial<Extract<Kommentar, object>> = {}): Kommentar => ({id: faker.number.int(), routenId: faker.number.int(), userId: faker.string.alpha({length: {min: 10, max: 20}}), datum: faker.date.past().toISOString().slice(0, 19) + 'Z', text: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})


export const getGetKommentareByRouteIDMockHandler = (overrideResponse?: Kommentar[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Kommentar[]> | Kommentar[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/kommentare', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetKommentareByRouteIDResponseMock(),
      { status: 200
      })
  }, options)
}

export const getAddKommentarMockHandler = (overrideResponse?: Kommentar | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Kommentar> | Kommentar), options?: RequestHandlerOptions) => {
  return http.post('*/api/kommentare', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getAddKommentarResponseMock(),
      { status: 201
      })
  }, options)
}

export const getDeleteKommentarMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/kommentare', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
  
    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getUpdateKommentarMockHandler = (overrideResponse?: Kommentar | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<Kommentar> | Kommentar), options?: RequestHandlerOptions) => {
  return http.patch('*/api/kommentare', async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateKommentarResponseMock(),
      { status: 200
      })
  }, options)
}
export const getKommentarControllerMock = () => [
  getGetKommentareByRouteIDMockHandler(),
  getAddKommentarMockHandler(),
  getDeleteKommentarMockHandler(),
  getUpdateKommentarMockHandler()
]
