/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteKommentarParams,
  GetKommentareByRouteIDParams,
  Kommentar,
  UpdateKommentarParams
} from '../model';





export type getKommentareByRouteIDResponse200 = {
  data: Blob
  status: 200
}

export type getKommentareByRouteIDResponse400 = {
  data: void
  status: 400
}

export type getKommentareByRouteIDResponse404 = {
  data: void
  status: 404
}

export type getKommentareByRouteIDResponse500 = {
  data: void
  status: 500
}

export type getKommentareByRouteIDResponseSuccess = (getKommentareByRouteIDResponse200) & {
  headers: Headers;
};
export type getKommentareByRouteIDResponseError = (getKommentareByRouteIDResponse400 | getKommentareByRouteIDResponse404 | getKommentareByRouteIDResponse500) & {
  headers: Headers;
};

export type getKommentareByRouteIDResponse = (getKommentareByRouteIDResponseSuccess | getKommentareByRouteIDResponseError)

export const getGetKommentareByRouteIDUrl = (params?: GetKommentareByRouteIDParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/kommentare?${stringifiedParams}` : `/api/kommentare`
}

export const getKommentareByRouteID = async (params?: GetKommentareByRouteIDParams, options?: RequestInit): Promise<getKommentareByRouteIDResponse> => {
  
  const res = await fetch(getGetKommentareByRouteIDUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getKommentareByRouteIDResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getKommentareByRouteIDResponse
}
  




export const getGetKommentareByRouteIDQueryKey = (params?: GetKommentareByRouteIDParams,) => {
    return [
    `/api/kommentare`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetKommentareByRouteIDQueryOptions = <TData = Awaited<ReturnType<typeof getKommentareByRouteID>>, TError = void>(params?: GetKommentareByRouteIDParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getKommentareByRouteID>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetKommentareByRouteIDQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getKommentareByRouteID>>> = ({ signal }) => getKommentareByRouteID(params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getKommentareByRouteID>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetKommentareByRouteIDQueryResult = NonNullable<Awaited<ReturnType<typeof getKommentareByRouteID>>>
export type GetKommentareByRouteIDQueryError = void


export function useGetKommentareByRouteID<TData = Awaited<ReturnType<typeof getKommentareByRouteID>>, TError = void>(
 params: undefined |  GetKommentareByRouteIDParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getKommentareByRouteID>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getKommentareByRouteID>>,
          TError,
          Awaited<ReturnType<typeof getKommentareByRouteID>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetKommentareByRouteID<TData = Awaited<ReturnType<typeof getKommentareByRouteID>>, TError = void>(
 params?: GetKommentareByRouteIDParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getKommentareByRouteID>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getKommentareByRouteID>>,
          TError,
          Awaited<ReturnType<typeof getKommentareByRouteID>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetKommentareByRouteID<TData = Awaited<ReturnType<typeof getKommentareByRouteID>>, TError = void>(
 params?: GetKommentareByRouteIDParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getKommentareByRouteID>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetKommentareByRouteID<TData = Awaited<ReturnType<typeof getKommentareByRouteID>>, TError = void>(
 params?: GetKommentareByRouteIDParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getKommentareByRouteID>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetKommentareByRouteIDQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type addKommentarResponse201 = {
  data: Blob
  status: 201
}

export type addKommentarResponse400 = {
  data: void
  status: 400
}

export type addKommentarResponse404 = {
  data: void
  status: 404
}

export type addKommentarResponse500 = {
  data: void
  status: 500
}

export type addKommentarResponseSuccess = (addKommentarResponse201) & {
  headers: Headers;
};
export type addKommentarResponseError = (addKommentarResponse400 | addKommentarResponse404 | addKommentarResponse500) & {
  headers: Headers;
};

export type addKommentarResponse = (addKommentarResponseSuccess | addKommentarResponseError)

export const getAddKommentarUrl = () => {


  

  return `/api/kommentare`
}

export const addKommentar = async (kommentar: Kommentar, options?: RequestInit): Promise<addKommentarResponse> => {
  
  const res = await fetch(getAddKommentarUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      kommentar,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: addKommentarResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as addKommentarResponse
}
  



export const getAddKommentarMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addKommentar>>, TError,{data: Kommentar}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof addKommentar>>, TError,{data: Kommentar}, TContext> => {

const mutationKey = ['addKommentar'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addKommentar>>, {data: Kommentar}> = (props) => {
          const {data} = props ?? {};

          return  addKommentar(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AddKommentarMutationResult = NonNullable<Awaited<ReturnType<typeof addKommentar>>>
    export type AddKommentarMutationBody = Kommentar
    export type AddKommentarMutationError = void

    export const useAddKommentar = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addKommentar>>, TError,{data: Kommentar}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addKommentar>>,
        TError,
        {data: Kommentar},
        TContext
      > => {
      return useMutation(getAddKommentarMutationOptions(options), queryClient);
    }
    export type deleteKommentarResponse204 = {
  data: void
  status: 204
}

export type deleteKommentarResponse400 = {
  data: void
  status: 400
}

export type deleteKommentarResponse404 = {
  data: void
  status: 404
}

export type deleteKommentarResponse500 = {
  data: void
  status: 500
}

export type deleteKommentarResponseSuccess = (deleteKommentarResponse204) & {
  headers: Headers;
};
export type deleteKommentarResponseError = (deleteKommentarResponse400 | deleteKommentarResponse404 | deleteKommentarResponse500) & {
  headers: Headers;
};

export type deleteKommentarResponse = (deleteKommentarResponseSuccess | deleteKommentarResponseError)

export const getDeleteKommentarUrl = (params: DeleteKommentarParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/kommentare?${stringifiedParams}` : `/api/kommentare`
}

export const deleteKommentar = async (params: DeleteKommentarParams, options?: RequestInit): Promise<deleteKommentarResponse> => {
  
  const res = await fetch(getDeleteKommentarUrl(params),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteKommentarResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteKommentarResponse
}
  



export const getDeleteKommentarMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteKommentar>>, TError,{params: DeleteKommentarParams}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteKommentar>>, TError,{params: DeleteKommentarParams}, TContext> => {

const mutationKey = ['deleteKommentar'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteKommentar>>, {params: DeleteKommentarParams}> = (props) => {
          const {params} = props ?? {};

          return  deleteKommentar(params,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteKommentarMutationResult = NonNullable<Awaited<ReturnType<typeof deleteKommentar>>>
    
    export type DeleteKommentarMutationError = void

    export const useDeleteKommentar = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteKommentar>>, TError,{params: DeleteKommentarParams}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteKommentar>>,
        TError,
        {params: DeleteKommentarParams},
        TContext
      > => {
      return useMutation(getDeleteKommentarMutationOptions(options), queryClient);
    }
    export type updateKommentarResponse200 = {
  data: Blob
  status: 200
}

export type updateKommentarResponse400 = {
  data: void
  status: 400
}

export type updateKommentarResponse404 = {
  data: void
  status: 404
}

export type updateKommentarResponse500 = {
  data: void
  status: 500
}

export type updateKommentarResponseSuccess = (updateKommentarResponse200) & {
  headers: Headers;
};
export type updateKommentarResponseError = (updateKommentarResponse400 | updateKommentarResponse404 | updateKommentarResponse500) & {
  headers: Headers;
};

export type updateKommentarResponse = (updateKommentarResponseSuccess | updateKommentarResponseError)

export const getUpdateKommentarUrl = (params: UpdateKommentarParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/kommentare?${stringifiedParams}` : `/api/kommentare`
}

export const updateKommentar = async (params: UpdateKommentarParams, options?: RequestInit): Promise<updateKommentarResponse> => {
  
  const res = await fetch(getUpdateKommentarUrl(params),
  {      
    ...options,
    method: 'PATCH'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateKommentarResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateKommentarResponse
}
  



export const getUpdateKommentarMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateKommentar>>, TError,{params: UpdateKommentarParams}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof updateKommentar>>, TError,{params: UpdateKommentarParams}, TContext> => {

const mutationKey = ['updateKommentar'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateKommentar>>, {params: UpdateKommentarParams}> = (props) => {
          const {params} = props ?? {};

          return  updateKommentar(params,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateKommentarMutationResult = NonNullable<Awaited<ReturnType<typeof updateKommentar>>>
    
    export type UpdateKommentarMutationError = void

    export const useUpdateKommentar = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateKommentar>>, TError,{params: UpdateKommentarParams}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateKommentar>>,
        TError,
        {params: UpdateKommentarParams},
        TContext
      > => {
      return useMutation(getUpdateKommentarMutationOptions(options), queryClient);
    }
    