/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteRouteParams,
  GetRoutenByHallenIdParams,
  Route
} from '../model';





export type getRoutenByHallenIdResponse200 = {
  data: Blob
  status: 200
}

export type getRoutenByHallenIdResponse400 = {
  data: void
  status: 400
}

export type getRoutenByHallenIdResponse404 = {
  data: void
  status: 404
}

export type getRoutenByHallenIdResponse500 = {
  data: void
  status: 500
}

export type getRoutenByHallenIdResponseSuccess = (getRoutenByHallenIdResponse200) & {
  headers: Headers;
};
export type getRoutenByHallenIdResponseError = (getRoutenByHallenIdResponse400 | getRoutenByHallenIdResponse404 | getRoutenByHallenIdResponse500) & {
  headers: Headers;
};

export type getRoutenByHallenIdResponse = (getRoutenByHallenIdResponseSuccess | getRoutenByHallenIdResponseError)

export const getGetRoutenByHallenIdUrl = (params: GetRoutenByHallenIdParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/routen?${stringifiedParams}` : `/api/routen`
}

export const getRoutenByHallenId = async (params: GetRoutenByHallenIdParams, options?: RequestInit): Promise<getRoutenByHallenIdResponse> => {
  
  const res = await fetch(getGetRoutenByHallenIdUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getRoutenByHallenIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getRoutenByHallenIdResponse
}
  




export const getGetRoutenByHallenIdQueryKey = (params?: GetRoutenByHallenIdParams,) => {
    return [
    `/api/routen`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetRoutenByHallenIdQueryOptions = <TData = Awaited<ReturnType<typeof getRoutenByHallenId>>, TError = void>(params: GetRoutenByHallenIdParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRoutenByHallenId>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRoutenByHallenIdQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRoutenByHallenId>>> = ({ signal }) => getRoutenByHallenId(params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRoutenByHallenId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetRoutenByHallenIdQueryResult = NonNullable<Awaited<ReturnType<typeof getRoutenByHallenId>>>
export type GetRoutenByHallenIdQueryError = void



export function useGetRoutenByHallenId<TData = Awaited<ReturnType<typeof getRoutenByHallenId>>, TError = void>(
 params: GetRoutenByHallenIdParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRoutenByHallenId>>, TError, TData>, fetch?: RequestInit}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetRoutenByHallenIdQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type addRouteResponse201 = {
  data: Blob
  status: 201
}

export type addRouteResponse400 = {
  data: void
  status: 400
}

export type addRouteResponse404 = {
  data: void
  status: 404
}

export type addRouteResponse500 = {
  data: void
  status: 500
}

export type addRouteResponseSuccess = (addRouteResponse201) & {
  headers: Headers;
};
export type addRouteResponseError = (addRouteResponse400 | addRouteResponse404 | addRouteResponse500) & {
  headers: Headers;
};

export type addRouteResponse = (addRouteResponseSuccess | addRouteResponseError)

export const getAddRouteUrl = () => {


  

  return `/api/routen`
}

export const addRoute = async (route: Route, options?: RequestInit): Promise<addRouteResponse> => {
  
  const res = await fetch(getAddRouteUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      route,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: addRouteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as addRouteResponse
}
  



export const getAddRouteMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addRoute>>, TError,{data: Route}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof addRoute>>, TError,{data: Route}, TContext> => {

const mutationKey = ['addRoute'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addRoute>>, {data: Route}> = (props) => {
          const {data} = props ?? {};

          return  addRoute(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AddRouteMutationResult = NonNullable<Awaited<ReturnType<typeof addRoute>>>
    export type AddRouteMutationBody = Route
    export type AddRouteMutationError = void

    export const useAddRoute = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addRoute>>, TError,{data: Route}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof addRoute>>,
        TError,
        {data: Route},
        TContext
      > => {
      return useMutation(getAddRouteMutationOptions(options));
    }
    export type deleteRouteResponse204 = {
  data: void
  status: 204
}

export type deleteRouteResponse400 = {
  data: void
  status: 400
}

export type deleteRouteResponse404 = {
  data: void
  status: 404
}

export type deleteRouteResponse500 = {
  data: void
  status: 500
}

export type deleteRouteResponseSuccess = (deleteRouteResponse204) & {
  headers: Headers;
};
export type deleteRouteResponseError = (deleteRouteResponse400 | deleteRouteResponse404 | deleteRouteResponse500) & {
  headers: Headers;
};

export type deleteRouteResponse = (deleteRouteResponseSuccess | deleteRouteResponseError)

export const getDeleteRouteUrl = (params: DeleteRouteParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/routen?${stringifiedParams}` : `/api/routen`
}

export const deleteRoute = async (params: DeleteRouteParams, options?: RequestInit): Promise<deleteRouteResponse> => {
  
  const res = await fetch(getDeleteRouteUrl(params),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteRouteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteRouteResponse
}
  



export const getDeleteRouteMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRoute>>, TError,{params: DeleteRouteParams}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteRoute>>, TError,{params: DeleteRouteParams}, TContext> => {

const mutationKey = ['deleteRoute'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteRoute>>, {params: DeleteRouteParams}> = (props) => {
          const {params} = props ?? {};

          return  deleteRoute(params,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteRouteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteRoute>>>
    
    export type DeleteRouteMutationError = void

    export const useDeleteRoute = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRoute>>, TError,{params: DeleteRouteParams}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteRoute>>,
        TError,
        {params: DeleteRouteParams},
        TContext
      > => {
      return useMutation(getDeleteRouteMutationOptions(options));
    }
    export type updateRouteResponse200 = {
  data: Blob
  status: 200
}

export type updateRouteResponse400 = {
  data: void
  status: 400
}

export type updateRouteResponse404 = {
  data: void
  status: 404
}

export type updateRouteResponse500 = {
  data: void
  status: 500
}

export type updateRouteResponseSuccess = (updateRouteResponse200) & {
  headers: Headers;
};
export type updateRouteResponseError = (updateRouteResponse400 | updateRouteResponse404 | updateRouteResponse500) & {
  headers: Headers;
};

export type updateRouteResponse = (updateRouteResponseSuccess | updateRouteResponseError)

export const getUpdateRouteUrl = () => {


  

  return `/api/routen`
}

export const updateRoute = async (route: Route, options?: RequestInit): Promise<updateRouteResponse> => {
  
  const res = await fetch(getUpdateRouteUrl(),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      route,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateRouteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateRouteResponse
}
  



export const getUpdateRouteMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRoute>>, TError,{data: Route}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof updateRoute>>, TError,{data: Route}, TContext> => {

const mutationKey = ['updateRoute'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateRoute>>, {data: Route}> = (props) => {
          const {data} = props ?? {};

          return  updateRoute(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateRouteMutationResult = NonNullable<Awaited<ReturnType<typeof updateRoute>>>
    export type UpdateRouteMutationBody = Route
    export type UpdateRouteMutationError = void

    export const useUpdateRoute = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRoute>>, TError,{data: Route}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateRoute>>,
        TError,
        {data: Route},
        TContext
      > => {
      return useMutation(getUpdateRouteMutationOptions(options));
    }
    