/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  FlachwitzData
} from '../model';

import { customFetch } from '../../utils/fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getGetFlachwitzOfTheDayUrl = () => {


  

  return `/api/flachwitz`
}

export const getFlachwitzOfTheDay = async ( options?: RequestInit): Promise<FlachwitzData> => {
  
  return customFetch<FlachwitzData>(getGetFlachwitzOfTheDayUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getGetFlachwitzOfTheDayQueryKey = () => {
    return [
    `/api/flachwitz`
    ] as const;
    }

    
export const getGetFlachwitzOfTheDayQueryOptions = <TData = Awaited<ReturnType<typeof getFlachwitzOfTheDay>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlachwitzOfTheDay>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFlachwitzOfTheDayQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFlachwitzOfTheDay>>> = ({ signal }) => getFlachwitzOfTheDay({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   retry: false, refetchOnReconnect: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFlachwitzOfTheDay>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFlachwitzOfTheDayQueryResult = NonNullable<Awaited<ReturnType<typeof getFlachwitzOfTheDay>>>
export type GetFlachwitzOfTheDayQueryError = void


export function useGetFlachwitzOfTheDay<TData = Awaited<ReturnType<typeof getFlachwitzOfTheDay>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlachwitzOfTheDay>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFlachwitzOfTheDay>>,
          TError,
          Awaited<ReturnType<typeof getFlachwitzOfTheDay>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFlachwitzOfTheDay<TData = Awaited<ReturnType<typeof getFlachwitzOfTheDay>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlachwitzOfTheDay>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFlachwitzOfTheDay>>,
          TError,
          Awaited<ReturnType<typeof getFlachwitzOfTheDay>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFlachwitzOfTheDay<TData = Awaited<ReturnType<typeof getFlachwitzOfTheDay>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlachwitzOfTheDay>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetFlachwitzOfTheDay<TData = Awaited<ReturnType<typeof getFlachwitzOfTheDay>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFlachwitzOfTheDay>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFlachwitzOfTheDayQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




