/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';


export const getGetUserRoutenStatusListResponseMock = (): ArrayBuffer => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({userId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), routenId: faker.helpers.arrayElement([faker.number.int(), undefined]), geschSchwierigkeit: faker.helpers.arrayElement([faker.number.float({fractionDigits: 2}), undefined]), notiz: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), favorit: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), projekt: faker.helpers.arrayElement([faker.datatype.boolean(), undefined])})))

export const getCreateUserRoutenStatusResponseMock = (overrideResponse: Partial<Extract<ArrayBuffer, object>> = {}): ArrayBuffer => ({userId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), routenId: faker.helpers.arrayElement([faker.number.int(), undefined]), geschSchwierigkeit: faker.helpers.arrayElement([faker.number.float({fractionDigits: 2}), undefined]), notiz: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), favorit: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), projekt: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), ...overrideResponse})

export const getUpdateUserRoutenStatusResponseMock = (overrideResponse: Partial<Extract<ArrayBuffer, object>> = {}): ArrayBuffer => ({userId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), routenId: faker.helpers.arrayElement([faker.number.int(), undefined]), geschSchwierigkeit: faker.helpers.arrayElement([faker.number.float({fractionDigits: 2}), undefined]), notiz: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), favorit: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), projekt: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), ...overrideResponse})


export const getGetUserRoutenStatusListMockHandler = (overrideResponse?: ArrayBuffer | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ArrayBuffer> | ArrayBuffer), options?: RequestHandlerOptions) => {
  return http.get('*/api/userroutenstatus', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  
  const binaryBody = overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetUserRoutenStatusListResponseMock();
    return HttpResponse.arrayBuffer(
      binaryBody instanceof ArrayBuffer
        ? binaryBody
        : new ArrayBuffer(0),
      { status: 200,
        headers: { 'Content-Type': 'application/octet-stream' }
      })
  }, options)
}

export const getCreateUserRoutenStatusMockHandler = (overrideResponse?: ArrayBuffer | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ArrayBuffer> | ArrayBuffer), options?: RequestHandlerOptions) => {
  return http.post('*/api/userroutenstatus', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  
  const binaryBody = overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateUserRoutenStatusResponseMock();
    return HttpResponse.arrayBuffer(
      binaryBody instanceof ArrayBuffer
        ? binaryBody
        : new ArrayBuffer(0),
      { status: 201,
        headers: { 'Content-Type': 'application/octet-stream' }
      })
  }, options)
}

export const getDeleteUserRoutenStatusMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/userroutenstatus', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
  
    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getUpdateUserRoutenStatusMockHandler = (overrideResponse?: ArrayBuffer | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<ArrayBuffer> | ArrayBuffer), options?: RequestHandlerOptions) => {
  return http.patch('*/api/userroutenstatus', async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
  
  const binaryBody = overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateUserRoutenStatusResponseMock();
    return HttpResponse.arrayBuffer(
      binaryBody instanceof ArrayBuffer
        ? binaryBody
        : new ArrayBuffer(0),
      { status: 200,
        headers: { 'Content-Type': 'application/octet-stream' }
      })
  }, options)
}
export const getUserRoutenStatusControllerMock = () => [
  getGetUserRoutenStatusListMockHandler(),
  getCreateUserRoutenStatusMockHandler(),
  getDeleteUserRoutenStatusMockHandler(),
  getUpdateUserRoutenStatusMockHandler()
]
