/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  UserRoutenStatus
} from '../model';


export const getGetUserRoutenStatusResponseMock = (overrideResponse: Partial<Extract<UserRoutenStatus, object>> = {}): UserRoutenStatus => ({userId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), routenId: faker.helpers.arrayElement([faker.number.int(), undefined]), isFavorit: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), isProjekt: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), geschSchwierigkeit: faker.helpers.arrayElement([faker.number.float({fractionDigits: 2}), undefined]), notiz: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), id: faker.helpers.arrayElement([{userId: faker.string.alpha({length: {min: 10, max: 20}}), routeId: faker.number.int()}, undefined]), ...overrideResponse})

export const getCreateUserRoutenStatusResponseMock = (overrideResponse: Partial<Extract<UserRoutenStatus, object>> = {}): UserRoutenStatus => ({userId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), routenId: faker.helpers.arrayElement([faker.number.int(), undefined]), isFavorit: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), isProjekt: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), geschSchwierigkeit: faker.helpers.arrayElement([faker.number.float({fractionDigits: 2}), undefined]), notiz: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), id: faker.helpers.arrayElement([{userId: faker.string.alpha({length: {min: 10, max: 20}}), routeId: faker.number.int()}, undefined]), ...overrideResponse})

export const getUpdateUserRoutenStatusResponseMock = (overrideResponse: Partial<Extract<UserRoutenStatus, object>> = {}): UserRoutenStatus => ({userId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), routenId: faker.helpers.arrayElement([faker.number.int(), undefined]), isFavorit: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), isProjekt: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), geschSchwierigkeit: faker.helpers.arrayElement([faker.number.float({fractionDigits: 2}), undefined]), notiz: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), id: faker.helpers.arrayElement([{userId: faker.string.alpha({length: {min: 10, max: 20}}), routeId: faker.number.int()}, undefined]), ...overrideResponse})


export const getGetUserRoutenStatusMockHandler = (overrideResponse?: UserRoutenStatus | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<UserRoutenStatus> | UserRoutenStatus), options?: RequestHandlerOptions) => {
  return http.get('*/api/userroutenstatus', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetUserRoutenStatusResponseMock(),
      { status: 200
      })
  }, options)
}

export const getCreateUserRoutenStatusMockHandler = (overrideResponse?: UserRoutenStatus | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<UserRoutenStatus> | UserRoutenStatus), options?: RequestHandlerOptions) => {
  return http.post('*/api/userroutenstatus', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateUserRoutenStatusResponseMock(),
      { status: 201
      })
  }, options)
}

export const getDeleteUserRoutenStatusMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/userroutenstatus', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
  
    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getUpdateUserRoutenStatusMockHandler = (overrideResponse?: UserRoutenStatus | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<UserRoutenStatus> | UserRoutenStatus), options?: RequestHandlerOptions) => {
  return http.patch('*/api/userroutenstatus', async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateUserRoutenStatusResponseMock(),
      { status: 200
      })
  }, options)
}
export const getUserRoutenStatusControllerMock = () => [
  getGetUserRoutenStatusMockHandler(),
  getCreateUserRoutenStatusMockHandler(),
  getDeleteUserRoutenStatusMockHandler(),
  getUpdateUserRoutenStatusMockHandler()
]
