/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteUserRoutenStatusParams,
  UserRoutenStatus
} from '../model';





export type getUserRoutenStatusListResponse200 = {
  data: Blob
  status: 200
}

export type getUserRoutenStatusListResponse400 = {
  data: void
  status: 400
}

export type getUserRoutenStatusListResponse404 = {
  data: void
  status: 404
}

export type getUserRoutenStatusListResponse500 = {
  data: void
  status: 500
}

export type getUserRoutenStatusListResponseSuccess = (getUserRoutenStatusListResponse200) & {
  headers: Headers;
};
export type getUserRoutenStatusListResponseError = (getUserRoutenStatusListResponse400 | getUserRoutenStatusListResponse404 | getUserRoutenStatusListResponse500) & {
  headers: Headers;
};

export type getUserRoutenStatusListResponse = (getUserRoutenStatusListResponseSuccess | getUserRoutenStatusListResponseError)

export const getGetUserRoutenStatusListUrl = () => {


  

  return `/api/userroutenstatus`
}

export const getUserRoutenStatusList = async ( options?: RequestInit): Promise<getUserRoutenStatusListResponse> => {
  
  const res = await fetch(getGetUserRoutenStatusListUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getUserRoutenStatusListResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getUserRoutenStatusListResponse
}
  




export const getGetUserRoutenStatusListQueryKey = () => {
    return [
    `/api/userroutenstatus`
    ] as const;
    }

    
export const getGetUserRoutenStatusListQueryOptions = <TData = Awaited<ReturnType<typeof getUserRoutenStatusList>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserRoutenStatusList>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserRoutenStatusListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserRoutenStatusList>>> = ({ signal }) => getUserRoutenStatusList({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserRoutenStatusList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserRoutenStatusListQueryResult = NonNullable<Awaited<ReturnType<typeof getUserRoutenStatusList>>>
export type GetUserRoutenStatusListQueryError = void


export function useGetUserRoutenStatusList<TData = Awaited<ReturnType<typeof getUserRoutenStatusList>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserRoutenStatusList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserRoutenStatusList>>,
          TError,
          Awaited<ReturnType<typeof getUserRoutenStatusList>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserRoutenStatusList<TData = Awaited<ReturnType<typeof getUserRoutenStatusList>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserRoutenStatusList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserRoutenStatusList>>,
          TError,
          Awaited<ReturnType<typeof getUserRoutenStatusList>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserRoutenStatusList<TData = Awaited<ReturnType<typeof getUserRoutenStatusList>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserRoutenStatusList>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUserRoutenStatusList<TData = Awaited<ReturnType<typeof getUserRoutenStatusList>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserRoutenStatusList>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserRoutenStatusListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type createUserRoutenStatusResponse201 = {
  data: Blob
  status: 201
}

export type createUserRoutenStatusResponse400 = {
  data: void
  status: 400
}

export type createUserRoutenStatusResponse404 = {
  data: void
  status: 404
}

export type createUserRoutenStatusResponse500 = {
  data: void
  status: 500
}

export type createUserRoutenStatusResponseSuccess = (createUserRoutenStatusResponse201) & {
  headers: Headers;
};
export type createUserRoutenStatusResponseError = (createUserRoutenStatusResponse400 | createUserRoutenStatusResponse404 | createUserRoutenStatusResponse500) & {
  headers: Headers;
};

export type createUserRoutenStatusResponse = (createUserRoutenStatusResponseSuccess | createUserRoutenStatusResponseError)

export const getCreateUserRoutenStatusUrl = () => {


  

  return `/api/userroutenstatus`
}

export const createUserRoutenStatus = async (userRoutenStatus: UserRoutenStatus, options?: RequestInit): Promise<createUserRoutenStatusResponse> => {
  
  const res = await fetch(getCreateUserRoutenStatusUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      userRoutenStatus,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createUserRoutenStatusResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createUserRoutenStatusResponse
}
  



export const getCreateUserRoutenStatusMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUserRoutenStatus>>, TError,{data: UserRoutenStatus}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createUserRoutenStatus>>, TError,{data: UserRoutenStatus}, TContext> => {

const mutationKey = ['createUserRoutenStatus'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createUserRoutenStatus>>, {data: UserRoutenStatus}> = (props) => {
          const {data} = props ?? {};

          return  createUserRoutenStatus(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateUserRoutenStatusMutationResult = NonNullable<Awaited<ReturnType<typeof createUserRoutenStatus>>>
    export type CreateUserRoutenStatusMutationBody = UserRoutenStatus
    export type CreateUserRoutenStatusMutationError = void

    export const useCreateUserRoutenStatus = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUserRoutenStatus>>, TError,{data: UserRoutenStatus}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createUserRoutenStatus>>,
        TError,
        {data: UserRoutenStatus},
        TContext
      > => {
      return useMutation(getCreateUserRoutenStatusMutationOptions(options), queryClient);
    }
    export type deleteUserRoutenStatusResponse204 = {
  data: void
  status: 204
}

export type deleteUserRoutenStatusResponse400 = {
  data: void
  status: 400
}

export type deleteUserRoutenStatusResponse404 = {
  data: void
  status: 404
}

export type deleteUserRoutenStatusResponse500 = {
  data: void
  status: 500
}

export type deleteUserRoutenStatusResponseSuccess = (deleteUserRoutenStatusResponse204) & {
  headers: Headers;
};
export type deleteUserRoutenStatusResponseError = (deleteUserRoutenStatusResponse400 | deleteUserRoutenStatusResponse404 | deleteUserRoutenStatusResponse500) & {
  headers: Headers;
};

export type deleteUserRoutenStatusResponse = (deleteUserRoutenStatusResponseSuccess | deleteUserRoutenStatusResponseError)

export const getDeleteUserRoutenStatusUrl = (params?: DeleteUserRoutenStatusParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/userroutenstatus?${stringifiedParams}` : `/api/userroutenstatus`
}

export const deleteUserRoutenStatus = async (params?: DeleteUserRoutenStatusParams, options?: RequestInit): Promise<deleteUserRoutenStatusResponse> => {
  
  const res = await fetch(getDeleteUserRoutenStatusUrl(params),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteUserRoutenStatusResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteUserRoutenStatusResponse
}
  



export const getDeleteUserRoutenStatusMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUserRoutenStatus>>, TError,{params?: DeleteUserRoutenStatusParams}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteUserRoutenStatus>>, TError,{params?: DeleteUserRoutenStatusParams}, TContext> => {

const mutationKey = ['deleteUserRoutenStatus'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUserRoutenStatus>>, {params?: DeleteUserRoutenStatusParams}> = (props) => {
          const {params} = props ?? {};

          return  deleteUserRoutenStatus(params,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteUserRoutenStatusMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUserRoutenStatus>>>
    
    export type DeleteUserRoutenStatusMutationError = void

    export const useDeleteUserRoutenStatus = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUserRoutenStatus>>, TError,{params?: DeleteUserRoutenStatusParams}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteUserRoutenStatus>>,
        TError,
        {params?: DeleteUserRoutenStatusParams},
        TContext
      > => {
      return useMutation(getDeleteUserRoutenStatusMutationOptions(options), queryClient);
    }
    export type updateUserRoutenStatusResponse200 = {
  data: Blob
  status: 200
}

export type updateUserRoutenStatusResponse400 = {
  data: void
  status: 400
}

export type updateUserRoutenStatusResponse404 = {
  data: void
  status: 404
}

export type updateUserRoutenStatusResponse500 = {
  data: void
  status: 500
}

export type updateUserRoutenStatusResponseSuccess = (updateUserRoutenStatusResponse200) & {
  headers: Headers;
};
export type updateUserRoutenStatusResponseError = (updateUserRoutenStatusResponse400 | updateUserRoutenStatusResponse404 | updateUserRoutenStatusResponse500) & {
  headers: Headers;
};

export type updateUserRoutenStatusResponse = (updateUserRoutenStatusResponseSuccess | updateUserRoutenStatusResponseError)

export const getUpdateUserRoutenStatusUrl = () => {


  

  return `/api/userroutenstatus`
}

export const updateUserRoutenStatus = async (userRoutenStatus: UserRoutenStatus, options?: RequestInit): Promise<updateUserRoutenStatusResponse> => {
  
  const res = await fetch(getUpdateUserRoutenStatusUrl(),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      userRoutenStatus,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateUserRoutenStatusResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateUserRoutenStatusResponse
}
  



export const getUpdateUserRoutenStatusMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUserRoutenStatus>>, TError,{data: UserRoutenStatus}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof updateUserRoutenStatus>>, TError,{data: UserRoutenStatus}, TContext> => {

const mutationKey = ['updateUserRoutenStatus'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUserRoutenStatus>>, {data: UserRoutenStatus}> = (props) => {
          const {data} = props ?? {};

          return  updateUserRoutenStatus(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateUserRoutenStatusMutationResult = NonNullable<Awaited<ReturnType<typeof updateUserRoutenStatus>>>
    export type UpdateUserRoutenStatusMutationBody = UserRoutenStatus
    export type UpdateUserRoutenStatusMutationError = void

    export const useUpdateUserRoutenStatus = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUserRoutenStatus>>, TError,{data: UserRoutenStatus}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateUserRoutenStatus>>,
        TError,
        {data: UserRoutenStatus},
        TContext
      > => {
      return useMutation(getUpdateUserRoutenStatusMutationOptions(options), queryClient);
    }
    