/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AscentSicherung } from './ascentSicherung';
import type { AscentStyle } from './ascentStyle';

export interface Ascent {
  id?: number;
  userId: string;
  routenId: number;
  datum: string;
  style?: AscentStyle;
  sicherung?: AscentSicherung;
}
