/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface Ascent {
  id?: number;
  userId: string;
  routenId: number;
  datum: string;
  style?: string;
  sicherung?: string;
}
