/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type AscentCreateDTOStyle = typeof AscentCreateDTOStyle[keyof typeof AscentCreateDTOStyle];


export const AscentCreateDTOStyle = {
  onsight: 'onsight',
  flash: 'flash',
  redpoint: 'redpoint',
  pinkpoint: 'pinkpoint',
  toprope: 'toprope',
  hangdog: 'hangdog',
  attempt: 'attempt',
} as const;
