/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type AscentResponseDTOSicherung = typeof AscentResponseDTOSicherung[keyof typeof AscentResponseDTOSicherung];


export const AscentResponseDTOSicherung = {
  vorstieg: 'vorstieg',
  toprope: 'toprope',
  solo: 'solo',
} as const;
