/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type AscentCreateDTOSicherung = typeof AscentCreateDTOSicherung[keyof typeof AscentCreateDTOSicherung];


export const AscentCreateDTOSicherung = {
  vorstieg: 'vorstieg',
  toprope: 'toprope',
  solo: 'solo',
} as const;
