/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AscentCreateDTOStyle } from './ascentCreateDTOStyle';

export interface AscentCreateDTO {
  userId: string;
  routenId: number;
  datum?: string;
  style?: AscentCreateDTOStyle;
}
