/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AscentResponseDTOSicherung } from './ascentResponseDTOSicherung';
import type { AscentResponseDTOStyle } from './ascentResponseDTOStyle';
import type { RouteResponseDTO } from './routeResponseDTO';

export interface AscentResponseDTO {
  id: number;
  userId: string;
  route: RouteResponseDTO;
  datum: string;
  style?: AscentResponseDTOStyle;
  sicherung?: AscentResponseDTOSicherung;
}
