/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface KommentarResponseDTO {
  id: number;
  routenId: number;
  username: string;
  datum: string;
  text: string;
}
