/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Route } from './route';
import type { User } from './user';

export interface Kommentar {
  id?: number;
  datum: string;
  text: string;
  route: Route;
  user: User;
}
