/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface NewsCreateDTO {
  hallenId?: number;
  autorId: string;
  titel: string;
  inhalt: string;
}
