/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Wand } from './wand';

export interface Route {
  id: number;
  name?: string;
  schwierigkeit?: number;
  farbe?: string;
  is_vorstieg?: boolean;
  is_toprope?: boolean;
  is_active?: boolean;
  schrauber?: string;
  schraubdatum?: string;
  beschreibung?: string;
  wand: Wand;
  hallenId?: number;
  wandNr?: number;
  isActive?: boolean;
}
