/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UserCreateDTO {
  keycloakId: string;
  name: string;
  bio?: string;
}
