/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UserRoutenStatus {
  userId?: string;
  routenId?: number;
  geschSchwierigkeit?: number;
  notiz?: string;
  favorit?: boolean;
  projekt?: boolean;
}
