/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserRoutenStatusId } from './userRoutenStatusId';

export interface UserRoutenStatus {
  userId?: string;
  routenId?: number;
  isFavorit?: boolean;
  isProjekt?: boolean;
  geschSchwierigkeit?: number;
  notiz?: string;
  id?: UserRoutenStatusId;
}
