/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Route } from './route';
import type { WandId } from './wandId';

export interface Wand {
  id: WandId;
  sektor?: string;
  startX: number;
  startY: number;
  endX: number;
  endY: number;
  position?: string;
  routen?: Route[];
}
