/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface WandCreateDTO {
  hallenId: number;
  wandNr: number;
  name?: string;
  startX: number;
  startY: number;
  endX: number;
  endY: number;
  position?: string;
}
