/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetAvatarParams,
  UploadAvatarBody,
  UploadAvatarParams
} from '../model';

import { customFetch } from '../../constants/fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getUploadAvatarUrl = (params: UploadAvatarParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/avatar/upload?${stringifiedParams}` : `/api/avatar/upload`
}

export const uploadAvatar = async (uploadAvatarBody: UploadAvatarBody,
    params: UploadAvatarParams, options?: RequestInit): Promise<Blob> => {
  
  return customFetch<Blob>(getUploadAvatarUrl(params),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      uploadAvatarBody,)
  }
);}
  



export const getUploadAvatarMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadAvatar>>, TError,{data: UploadAvatarBody;params: UploadAvatarParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof uploadAvatar>>, TError,{data: UploadAvatarBody;params: UploadAvatarParams}, TContext> => {

const mutationKey = ['uploadAvatar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadAvatar>>, {data: UploadAvatarBody;params: UploadAvatarParams}> = (props) => {
          const {data,params} = props ?? {};

          return  uploadAvatar(data,params,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UploadAvatarMutationResult = NonNullable<Awaited<ReturnType<typeof uploadAvatar>>>
    export type UploadAvatarMutationBody = UploadAvatarBody
    export type UploadAvatarMutationError = void

    export const useUploadAvatar = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadAvatar>>, TError,{data: UploadAvatarBody;params: UploadAvatarParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadAvatar>>,
        TError,
        {data: UploadAvatarBody;params: UploadAvatarParams},
        TContext
      > => {
      return useMutation(getUploadAvatarMutationOptions(options), queryClient);
    }
    export const getGetAvatarUrl = (params: GetAvatarParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/avatar?${stringifiedParams}` : `/api/avatar`
}

export const getAvatar = async (params: GetAvatarParams, options?: RequestInit): Promise<Blob> => {
  
  return customFetch<Blob>(getGetAvatarUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getGetAvatarQueryKey = (params?: GetAvatarParams,) => {
    return [
    `/api/avatar`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetAvatarQueryOptions = <TData = Awaited<ReturnType<typeof getAvatar>>, TError = void>(params: GetAvatarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAvatar>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAvatarQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAvatar>>> = ({ signal }) => getAvatar(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAvatar>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAvatarQueryResult = NonNullable<Awaited<ReturnType<typeof getAvatar>>>
export type GetAvatarQueryError = void


export function useGetAvatar<TData = Awaited<ReturnType<typeof getAvatar>>, TError = void>(
 params: GetAvatarParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAvatar>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAvatar>>,
          TError,
          Awaited<ReturnType<typeof getAvatar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAvatar<TData = Awaited<ReturnType<typeof getAvatar>>, TError = void>(
 params: GetAvatarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAvatar>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAvatar>>,
          TError,
          Awaited<ReturnType<typeof getAvatar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAvatar<TData = Awaited<ReturnType<typeof getAvatar>>, TError = void>(
 params: GetAvatarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAvatar>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAvatar<TData = Awaited<ReturnType<typeof getAvatar>>, TError = void>(
 params: GetAvatarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAvatar>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAvatarQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




