/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteHalleParams,
  FindHalleParams,
  Halle
} from '../model';





export type findHalleResponse200 = {
  data: Halle[]
  status: 200
}

export type findHalleResponse400 = {
  data: void
  status: 400
}

export type findHalleResponse404 = {
  data: void
  status: 404
}

export type findHalleResponse500 = {
  data: void
  status: 500
}

export type findHalleResponseSuccess = (findHalleResponse200) & {
  headers: Headers;
};
export type findHalleResponseError = (findHalleResponse400 | findHalleResponse404 | findHalleResponse500) & {
  headers: Headers;
};

export type findHalleResponse = (findHalleResponseSuccess | findHalleResponseError)

export const getFindHalleUrl = (params?: FindHalleParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/hallen?${stringifiedParams}` : `/api/hallen`
}

export const findHalle = async (params?: FindHalleParams, options?: RequestInit): Promise<findHalleResponse> => {
  
  const res = await fetch(getFindHalleUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: findHalleResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as findHalleResponse
}
  




export const getFindHalleQueryKey = (params?: FindHalleParams,) => {
    return [
    `/api/hallen`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getFindHalleQueryOptions = <TData = Awaited<ReturnType<typeof findHalle>>, TError = void>(params?: FindHalleParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findHalle>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindHalleQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findHalle>>> = ({ signal }) => findHalle(params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findHalle>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindHalleQueryResult = NonNullable<Awaited<ReturnType<typeof findHalle>>>
export type FindHalleQueryError = void


export function useFindHalle<TData = Awaited<ReturnType<typeof findHalle>>, TError = void>(
 params: undefined |  FindHalleParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findHalle>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findHalle>>,
          TError,
          Awaited<ReturnType<typeof findHalle>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindHalle<TData = Awaited<ReturnType<typeof findHalle>>, TError = void>(
 params?: FindHalleParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findHalle>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findHalle>>,
          TError,
          Awaited<ReturnType<typeof findHalle>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindHalle<TData = Awaited<ReturnType<typeof findHalle>>, TError = void>(
 params?: FindHalleParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findHalle>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFindHalle<TData = Awaited<ReturnType<typeof findHalle>>, TError = void>(
 params?: FindHalleParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findHalle>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindHalleQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type addHalleResponse201 = {
  data: Halle
  status: 201
}

export type addHalleResponse400 = {
  data: void
  status: 400
}

export type addHalleResponse404 = {
  data: void
  status: 404
}

export type addHalleResponse500 = {
  data: void
  status: 500
}

export type addHalleResponseSuccess = (addHalleResponse201) & {
  headers: Headers;
};
export type addHalleResponseError = (addHalleResponse400 | addHalleResponse404 | addHalleResponse500) & {
  headers: Headers;
};

export type addHalleResponse = (addHalleResponseSuccess | addHalleResponseError)

export const getAddHalleUrl = () => {


  

  return `/api/hallen`
}

export const addHalle = async (halle: Halle, options?: RequestInit): Promise<addHalleResponse> => {
  
  const res = await fetch(getAddHalleUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      halle,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: addHalleResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as addHalleResponse
}
  



export const getAddHalleMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addHalle>>, TError,{data: Halle}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof addHalle>>, TError,{data: Halle}, TContext> => {

const mutationKey = ['addHalle'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addHalle>>, {data: Halle}> = (props) => {
          const {data} = props ?? {};

          return  addHalle(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AddHalleMutationResult = NonNullable<Awaited<ReturnType<typeof addHalle>>>
    export type AddHalleMutationBody = Halle
    export type AddHalleMutationError = void

    export const useAddHalle = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addHalle>>, TError,{data: Halle}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addHalle>>,
        TError,
        {data: Halle},
        TContext
      > => {
      return useMutation(getAddHalleMutationOptions(options), queryClient);
    }
    export type deleteHalleResponse204 = {
  data: void
  status: 204
}

export type deleteHalleResponse400 = {
  data: void
  status: 400
}

export type deleteHalleResponse404 = {
  data: void
  status: 404
}

export type deleteHalleResponse500 = {
  data: void
  status: 500
}

export type deleteHalleResponseSuccess = (deleteHalleResponse204) & {
  headers: Headers;
};
export type deleteHalleResponseError = (deleteHalleResponse400 | deleteHalleResponse404 | deleteHalleResponse500) & {
  headers: Headers;
};

export type deleteHalleResponse = (deleteHalleResponseSuccess | deleteHalleResponseError)

export const getDeleteHalleUrl = (params: DeleteHalleParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/hallen?${stringifiedParams}` : `/api/hallen`
}

export const deleteHalle = async (params: DeleteHalleParams, options?: RequestInit): Promise<deleteHalleResponse> => {
  
  const res = await fetch(getDeleteHalleUrl(params),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteHalleResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteHalleResponse
}
  



export const getDeleteHalleMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteHalle>>, TError,{params: DeleteHalleParams}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteHalle>>, TError,{params: DeleteHalleParams}, TContext> => {

const mutationKey = ['deleteHalle'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteHalle>>, {params: DeleteHalleParams}> = (props) => {
          const {params} = props ?? {};

          return  deleteHalle(params,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteHalleMutationResult = NonNullable<Awaited<ReturnType<typeof deleteHalle>>>
    
    export type DeleteHalleMutationError = void

    export const useDeleteHalle = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteHalle>>, TError,{params: DeleteHalleParams}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteHalle>>,
        TError,
        {params: DeleteHalleParams},
        TContext
      > => {
      return useMutation(getDeleteHalleMutationOptions(options), queryClient);
    }
    export type updateHalleResponse200 = {
  data: Halle
  status: 200
}

export type updateHalleResponse400 = {
  data: void
  status: 400
}

export type updateHalleResponse404 = {
  data: void
  status: 404
}

export type updateHalleResponse500 = {
  data: void
  status: 500
}

export type updateHalleResponseSuccess = (updateHalleResponse200) & {
  headers: Headers;
};
export type updateHalleResponseError = (updateHalleResponse400 | updateHalleResponse404 | updateHalleResponse500) & {
  headers: Headers;
};

export type updateHalleResponse = (updateHalleResponseSuccess | updateHalleResponseError)

export const getUpdateHalleUrl = () => {


  

  return `/api/hallen`
}

export const updateHalle = async (halle: Halle, options?: RequestInit): Promise<updateHalleResponse> => {
  
  const res = await fetch(getUpdateHalleUrl(),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      halle,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateHalleResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateHalleResponse
}
  



export const getUpdateHalleMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateHalle>>, TError,{data: Halle}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof updateHalle>>, TError,{data: Halle}, TContext> => {

const mutationKey = ['updateHalle'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateHalle>>, {data: Halle}> = (props) => {
          const {data} = props ?? {};

          return  updateHalle(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateHalleMutationResult = NonNullable<Awaited<ReturnType<typeof updateHalle>>>
    export type UpdateHalleMutationBody = Halle
    export type UpdateHalleMutationError = void

    export const useUpdateHalle = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateHalle>>, TError,{data: Halle}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateHalle>>,
        TError,
        {data: Halle},
        TContext
      > => {
      return useMutation(getUpdateHalleMutationOptions(options), queryClient);
    }
    