/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  Halle
} from '../model';


export const getFindHalleResponseMock = (): Halle[] => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.number.int(), name: faker.string.alpha({length: {min: 10, max: 20}}), adresse: faker.string.alpha({length: {min: 10, max: 20}}), betreiber: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])})))

export const getAddHalleResponseMock = (overrideResponse: Partial<Extract<Halle, object>> = {}): Halle => ({id: faker.number.int(), name: faker.string.alpha({length: {min: 10, max: 20}}), adresse: faker.string.alpha({length: {min: 10, max: 20}}), betreiber: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), ...overrideResponse})

export const getUpdateHalleResponseMock = (overrideResponse: Partial<Extract<Halle, object>> = {}): Halle => ({id: faker.number.int(), name: faker.string.alpha({length: {min: 10, max: 20}}), adresse: faker.string.alpha({length: {min: 10, max: 20}}), betreiber: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), ...overrideResponse})


export const getFindHalleMockHandler = (overrideResponse?: Halle[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Halle[]> | Halle[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/hallen', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getFindHalleResponseMock(),
      { status: 200
      })
  }, options)
}

export const getAddHalleMockHandler = (overrideResponse?: Halle | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Halle> | Halle), options?: RequestHandlerOptions) => {
  return http.post('*/api/hallen', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getAddHalleResponseMock(),
      { status: 201
      })
  }, options)
}

export const getDeleteHalleMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/hallen', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
  
    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getUpdateHalleMockHandler = (overrideResponse?: Halle | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<Halle> | Halle), options?: RequestHandlerOptions) => {
  return http.patch('*/api/hallen', async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateHalleResponseMock(),
      { status: 200
      })
  }, options)
}
export const getHallenControllerMock = () => [
  getFindHalleMockHandler(),
  getAddHalleMockHandler(),
  getDeleteHalleMockHandler(),
  getUpdateHalleMockHandler()
]
