/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AscentCreateDTO,
  AscentResponseDTO,
  DeleteAscentParams,
  FindAscentsParams,
  UpdateAscentParams
} from '../model';

import { customFetch } from '../../constants/fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getFindAscentsUrl = (params: FindAscentsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/ascents?${stringifiedParams}` : `/api/ascents`
}

export const findAscents = async (params: FindAscentsParams, options?: RequestInit): Promise<AscentResponseDTO[]> => {
  
  return customFetch<AscentResponseDTO[]>(getFindAscentsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getFindAscentsQueryKey = (params?: FindAscentsParams,) => {
    return [
    `/api/ascents`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getFindAscentsQueryOptions = <TData = Awaited<ReturnType<typeof findAscents>>, TError = void>(params: FindAscentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAscents>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindAscentsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findAscents>>> = ({ signal }) => findAscents(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   retry: false, refetchOnReconnect: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findAscents>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindAscentsQueryResult = NonNullable<Awaited<ReturnType<typeof findAscents>>>
export type FindAscentsQueryError = void


export function useFindAscents<TData = Awaited<ReturnType<typeof findAscents>>, TError = void>(
 params: FindAscentsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAscents>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findAscents>>,
          TError,
          Awaited<ReturnType<typeof findAscents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindAscents<TData = Awaited<ReturnType<typeof findAscents>>, TError = void>(
 params: FindAscentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAscents>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findAscents>>,
          TError,
          Awaited<ReturnType<typeof findAscents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindAscents<TData = Awaited<ReturnType<typeof findAscents>>, TError = void>(
 params: FindAscentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAscents>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFindAscents<TData = Awaited<ReturnType<typeof findAscents>>, TError = void>(
 params: FindAscentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAscents>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindAscentsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getAddAscentUrl = () => {


  

  return `/api/ascents`
}

export const addAscent = async (ascentCreateDTO: AscentCreateDTO, options?: RequestInit): Promise<AscentResponseDTO> => {
  
  return customFetch<AscentResponseDTO>(getAddAscentUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      ascentCreateDTO,)
  }
);}
  



export const getAddAscentMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addAscent>>, TError,{data: AscentCreateDTO}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof addAscent>>, TError,{data: AscentCreateDTO}, TContext> => {

const mutationKey = ['addAscent'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addAscent>>, {data: AscentCreateDTO}> = (props) => {
          const {data} = props ?? {};

          return  addAscent(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AddAscentMutationResult = NonNullable<Awaited<ReturnType<typeof addAscent>>>
    export type AddAscentMutationBody = AscentCreateDTO
    export type AddAscentMutationError = void

    export const useAddAscent = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addAscent>>, TError,{data: AscentCreateDTO}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addAscent>>,
        TError,
        {data: AscentCreateDTO},
        TContext
      > => {
      return useMutation(getAddAscentMutationOptions(options), queryClient);
    }
    export const getDeleteAscentUrl = (params: DeleteAscentParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/ascents?${stringifiedParams}` : `/api/ascents`
}

export const deleteAscent = async (params: DeleteAscentParams, options?: RequestInit): Promise<void> => {
  
  return customFetch<void>(getDeleteAscentUrl(params),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  



export const getDeleteAscentMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAscent>>, TError,{params: DeleteAscentParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAscent>>, TError,{params: DeleteAscentParams}, TContext> => {

const mutationKey = ['deleteAscent'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAscent>>, {params: DeleteAscentParams}> = (props) => {
          const {params} = props ?? {};

          return  deleteAscent(params,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAscentMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAscent>>>
    
    export type DeleteAscentMutationError = void

    export const useDeleteAscent = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAscent>>, TError,{params: DeleteAscentParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAscent>>,
        TError,
        {params: DeleteAscentParams},
        TContext
      > => {
      return useMutation(getDeleteAscentMutationOptions(options), queryClient);
    }
    export const getUpdateAscentUrl = (params: UpdateAscentParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/ascents?${stringifiedParams}` : `/api/ascents`
}

export const updateAscent = async (ascentCreateDTO: AscentCreateDTO,
    params: UpdateAscentParams, options?: RequestInit): Promise<AscentResponseDTO> => {
  
  return customFetch<AscentResponseDTO>(getUpdateAscentUrl(params),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      ascentCreateDTO,)
  }
);}
  



export const getUpdateAscentMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAscent>>, TError,{data: AscentCreateDTO;params: UpdateAscentParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateAscent>>, TError,{data: AscentCreateDTO;params: UpdateAscentParams}, TContext> => {

const mutationKey = ['updateAscent'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateAscent>>, {data: AscentCreateDTO;params: UpdateAscentParams}> = (props) => {
          const {data,params} = props ?? {};

          return  updateAscent(data,params,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateAscentMutationResult = NonNullable<Awaited<ReturnType<typeof updateAscent>>>
    export type UpdateAscentMutationBody = AscentCreateDTO
    export type UpdateAscentMutationError = void

    export const useUpdateAscent = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAscent>>, TError,{data: AscentCreateDTO;params: UpdateAscentParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateAscent>>,
        TError,
        {data: AscentCreateDTO;params: UpdateAscentParams},
        TContext
      > => {
      return useMutation(getUpdateAscentMutationOptions(options), queryClient);
    }
    