/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';


export const getFindAscentsByUserIdResponseMock = (): ArrayBuffer => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), userId: faker.string.alpha({length: {min: 10, max: 20}}), routenId: faker.number.int(), datum: faker.date.past().toISOString().slice(0, 19) + 'Z', style: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), sicherung: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])})))

export const getAddAscentResponseMock = (overrideResponse: Partial<Extract<ArrayBuffer, object>> = {}): ArrayBuffer => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), userId: faker.string.alpha({length: {min: 10, max: 20}}), routenId: faker.number.int(), datum: faker.date.past().toISOString().slice(0, 19) + 'Z', style: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), sicherung: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), ...overrideResponse})

export const getUpdateAscentResponseMock = (overrideResponse: Partial<Extract<ArrayBuffer, object>> = {}): ArrayBuffer => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), userId: faker.string.alpha({length: {min: 10, max: 20}}), routenId: faker.number.int(), datum: faker.date.past().toISOString().slice(0, 19) + 'Z', style: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), sicherung: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), ...overrideResponse})


export const getFindAscentsByUserIdMockHandler = (overrideResponse?: ArrayBuffer | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ArrayBuffer> | ArrayBuffer), options?: RequestHandlerOptions) => {
  return http.get('*/api/ascents', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  
  const binaryBody = overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getFindAscentsByUserIdResponseMock();
    return HttpResponse.arrayBuffer(
      binaryBody instanceof ArrayBuffer
        ? binaryBody
        : new ArrayBuffer(0),
      { status: 200,
        headers: { 'Content-Type': 'application/octet-stream' }
      })
  }, options)
}

export const getAddAscentMockHandler = (overrideResponse?: ArrayBuffer | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ArrayBuffer> | ArrayBuffer), options?: RequestHandlerOptions) => {
  return http.post('*/api/ascents', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  
  const binaryBody = overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getAddAscentResponseMock();
    return HttpResponse.arrayBuffer(
      binaryBody instanceof ArrayBuffer
        ? binaryBody
        : new ArrayBuffer(0),
      { status: 201,
        headers: { 'Content-Type': 'application/octet-stream' }
      })
  }, options)
}

export const getDeleteAscentMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/ascents', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
  
    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getUpdateAscentMockHandler = (overrideResponse?: ArrayBuffer | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<ArrayBuffer> | ArrayBuffer), options?: RequestHandlerOptions) => {
  return http.patch('*/api/ascents', async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
  
  const binaryBody = overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateAscentResponseMock();
    return HttpResponse.arrayBuffer(
      binaryBody instanceof ArrayBuffer
        ? binaryBody
        : new ArrayBuffer(0),
      { status: 200,
        headers: { 'Content-Type': 'application/octet-stream' }
      })
  }, options)
}
export const getAscentControllerMock = () => [
  getFindAscentsByUserIdMockHandler(),
  getAddAscentMockHandler(),
  getDeleteAscentMockHandler(),
  getUpdateAscentMockHandler()
]
