/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  Ascent
} from '../model';


export const getFindAscentsByUserIdResponseMock = (): Ascent[] => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), userId: faker.string.alpha({length: {min: 10, max: 20}}), routenId: faker.number.int(), datum: faker.date.past().toISOString().slice(0, 10), style: faker.helpers.arrayElement([faker.helpers.arrayElement(['onsight','flash','redpoint','pinkpoint','toprope','hangdog','attempt'] as const), undefined]), sicherung: faker.helpers.arrayElement([faker.helpers.arrayElement(['vorstieg','toprope','solo'] as const), undefined])})))

export const getAddAscentResponseMock = (overrideResponse: Partial<Extract<Ascent, object>> = {}): Ascent => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), userId: faker.string.alpha({length: {min: 10, max: 20}}), routenId: faker.number.int(), datum: faker.date.past().toISOString().slice(0, 10), style: faker.helpers.arrayElement([faker.helpers.arrayElement(['onsight','flash','redpoint','pinkpoint','toprope','hangdog','attempt'] as const), undefined]), sicherung: faker.helpers.arrayElement([faker.helpers.arrayElement(['vorstieg','toprope','solo'] as const), undefined]), ...overrideResponse})

export const getUpdateAscentResponseMock = (overrideResponse: Partial<Extract<Ascent, object>> = {}): Ascent => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), userId: faker.string.alpha({length: {min: 10, max: 20}}), routenId: faker.number.int(), datum: faker.date.past().toISOString().slice(0, 10), style: faker.helpers.arrayElement([faker.helpers.arrayElement(['onsight','flash','redpoint','pinkpoint','toprope','hangdog','attempt'] as const), undefined]), sicherung: faker.helpers.arrayElement([faker.helpers.arrayElement(['vorstieg','toprope','solo'] as const), undefined]), ...overrideResponse})


export const getFindAscentsByUserIdMockHandler = (overrideResponse?: Ascent[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Ascent[]> | Ascent[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/ascents', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getFindAscentsByUserIdResponseMock(),
      { status: 200
      })
  }, options)
}

export const getAddAscentMockHandler = (overrideResponse?: Ascent | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Ascent> | Ascent), options?: RequestHandlerOptions) => {
  return http.post('*/api/ascents', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getAddAscentResponseMock(),
      { status: 201
      })
  }, options)
}

export const getDeleteAscentMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/ascents', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
  
    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getUpdateAscentMockHandler = (overrideResponse?: Ascent | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<Ascent> | Ascent), options?: RequestHandlerOptions) => {
  return http.patch('*/api/ascents', async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateAscentResponseMock(),
      { status: 200
      })
  }, options)
}
export const getAscentControllerMock = () => [
  getFindAscentsByUserIdMockHandler(),
  getAddAscentMockHandler(),
  getDeleteAscentMockHandler(),
  getUpdateAscentMockHandler()
]
