/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  User
} from '../model';


export const getGetUserResponseMock = (overrideResponse: Partial<Extract<User, object>> = {}): User => ({name: faker.string.alpha({length: {min: 10, max: 20}}), keycloakId: faker.string.alpha({length: {min: 10, max: 20}}), bildUrl: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), bio: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), ...overrideResponse})

export const getSyncUserResponseMock = (overrideResponse: Partial<Extract<User, object>> = {}): User => ({name: faker.string.alpha({length: {min: 10, max: 20}}), keycloakId: faker.string.alpha({length: {min: 10, max: 20}}), bildUrl: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), bio: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), ...overrideResponse})

export const getChangeUserResponseMock = (overrideResponse: Partial<Extract<User, object>> = {}): User => ({name: faker.string.alpha({length: {min: 10, max: 20}}), keycloakId: faker.string.alpha({length: {min: 10, max: 20}}), bildUrl: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), bio: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), ...overrideResponse})


export const getGetUserMockHandler = (overrideResponse?: User | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<User> | User), options?: RequestHandlerOptions) => {
  return http.get('*/api/users', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetUserResponseMock(),
      { status: 200
      })
  }, options)
}

export const getSyncUserMockHandler = (overrideResponse?: User | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<User> | User), options?: RequestHandlerOptions) => {
  return http.post('*/api/users', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getSyncUserResponseMock(),
      { status: 200
      })
  }, options)
}

export const getDeleteUserMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/users', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
  
    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getChangeUserMockHandler = (overrideResponse?: User | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<User> | User), options?: RequestHandlerOptions) => {
  return http.patch('*/api/users', async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getChangeUserResponseMock(),
      { status: 200
      })
  }, options)
}
export const getUserControllerMock = () => [
  getGetUserMockHandler(),
  getSyncUserMockHandler(),
  getDeleteUserMockHandler(),
  getChangeUserMockHandler()
]
