/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteUserParams,
  GetUserParams,
  User,
  UserSyncRequest
} from '../model';





export type getUserResponse200 = {
  data: User
  status: 200
}

export type getUserResponse400 = {
  data: void
  status: 400
}

export type getUserResponse404 = {
  data: void
  status: 404
}

export type getUserResponse500 = {
  data: void
  status: 500
}

export type getUserResponseSuccess = (getUserResponse200) & {
  headers: Headers;
};
export type getUserResponseError = (getUserResponse400 | getUserResponse404 | getUserResponse500) & {
  headers: Headers;
};

export type getUserResponse = (getUserResponseSuccess | getUserResponseError)

export const getGetUserUrl = (params: GetUserParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/users?${stringifiedParams}` : `/api/users`
}

export const getUser = async (params: GetUserParams, options?: RequestInit): Promise<getUserResponse> => {
  
  const res = await fetch(getGetUserUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getUserResponse
}
  




export const getGetUserQueryKey = (params?: GetUserParams,) => {
    return [
    `/api/users`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetUserQueryOptions = <TData = Awaited<ReturnType<typeof getUser>>, TError = void>(params: GetUserParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUser>>> = ({ signal }) => getUser(params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserQueryResult = NonNullable<Awaited<ReturnType<typeof getUser>>>
export type GetUserQueryError = void


export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = void>(
 params: GetUserParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUser>>,
          TError,
          Awaited<ReturnType<typeof getUser>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = void>(
 params: GetUserParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUser>>,
          TError,
          Awaited<ReturnType<typeof getUser>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = void>(
 params: GetUserParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = void>(
 params: GetUserParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type syncUserResponse200 = {
  data: User
  status: 200
}

export type syncUserResponse400 = {
  data: void
  status: 400
}

export type syncUserResponse404 = {
  data: void
  status: 404
}

export type syncUserResponse500 = {
  data: void
  status: 500
}

export type syncUserResponseSuccess = (syncUserResponse200) & {
  headers: Headers;
};
export type syncUserResponseError = (syncUserResponse400 | syncUserResponse404 | syncUserResponse500) & {
  headers: Headers;
};

export type syncUserResponse = (syncUserResponseSuccess | syncUserResponseError)

export const getSyncUserUrl = () => {


  

  return `/api/users`
}

export const syncUser = async (userSyncRequest: UserSyncRequest, options?: RequestInit): Promise<syncUserResponse> => {
  
  const res = await fetch(getSyncUserUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      userSyncRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: syncUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as syncUserResponse
}
  



export const getSyncUserMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncUser>>, TError,{data: UserSyncRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof syncUser>>, TError,{data: UserSyncRequest}, TContext> => {

const mutationKey = ['syncUser'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof syncUser>>, {data: UserSyncRequest}> = (props) => {
          const {data} = props ?? {};

          return  syncUser(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type SyncUserMutationResult = NonNullable<Awaited<ReturnType<typeof syncUser>>>
    export type SyncUserMutationBody = UserSyncRequest
    export type SyncUserMutationError = void

    export const useSyncUser = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncUser>>, TError,{data: UserSyncRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof syncUser>>,
        TError,
        {data: UserSyncRequest},
        TContext
      > => {
      return useMutation(getSyncUserMutationOptions(options), queryClient);
    }
    export type deleteUserResponse204 = {
  data: void
  status: 204
}

export type deleteUserResponse400 = {
  data: void
  status: 400
}

export type deleteUserResponse404 = {
  data: void
  status: 404
}

export type deleteUserResponse500 = {
  data: void
  status: 500
}

export type deleteUserResponseSuccess = (deleteUserResponse204) & {
  headers: Headers;
};
export type deleteUserResponseError = (deleteUserResponse400 | deleteUserResponse404 | deleteUserResponse500) & {
  headers: Headers;
};

export type deleteUserResponse = (deleteUserResponseSuccess | deleteUserResponseError)

export const getDeleteUserUrl = (params: DeleteUserParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/users?${stringifiedParams}` : `/api/users`
}

export const deleteUser = async (params: DeleteUserParams, options?: RequestInit): Promise<deleteUserResponse> => {
  
  const res = await fetch(getDeleteUserUrl(params),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteUserResponse
}
  



export const getDeleteUserMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{params: DeleteUserParams}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{params: DeleteUserParams}, TContext> => {

const mutationKey = ['deleteUser'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUser>>, {params: DeleteUserParams}> = (props) => {
          const {params} = props ?? {};

          return  deleteUser(params,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteUserMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUser>>>
    
    export type DeleteUserMutationError = void

    export const useDeleteUser = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{params: DeleteUserParams}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteUser>>,
        TError,
        {params: DeleteUserParams},
        TContext
      > => {
      return useMutation(getDeleteUserMutationOptions(options), queryClient);
    }
    export type changeUserResponse200 = {
  data: User
  status: 200
}

export type changeUserResponse400 = {
  data: void
  status: 400
}

export type changeUserResponse404 = {
  data: void
  status: 404
}

export type changeUserResponse500 = {
  data: void
  status: 500
}

export type changeUserResponseSuccess = (changeUserResponse200) & {
  headers: Headers;
};
export type changeUserResponseError = (changeUserResponse400 | changeUserResponse404 | changeUserResponse500) & {
  headers: Headers;
};

export type changeUserResponse = (changeUserResponseSuccess | changeUserResponseError)

export const getChangeUserUrl = () => {


  

  return `/api/users`
}

export const changeUser = async (user: User, options?: RequestInit): Promise<changeUserResponse> => {
  
  const res = await fetch(getChangeUserUrl(),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      user,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: changeUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as changeUserResponse
}
  



export const getChangeUserMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changeUser>>, TError,{data: User}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof changeUser>>, TError,{data: User}, TContext> => {

const mutationKey = ['changeUser'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof changeUser>>, {data: User}> = (props) => {
          const {data} = props ?? {};

          return  changeUser(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ChangeUserMutationResult = NonNullable<Awaited<ReturnType<typeof changeUser>>>
    export type ChangeUserMutationBody = User
    export type ChangeUserMutationError = void

    export const useChangeUser = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changeUser>>, TError,{data: User}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof changeUser>>,
        TError,
        {data: User},
        TContext
      > => {
      return useMutation(getChangeUserMutationOptions(options), queryClient);
    }
    