/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteWandParams,
  GetWaendeByHallenIdParams,
  Wand
} from '../model';





export type getWaendeByHallenIdResponse200 = {
  data: Blob
  status: 200
}

export type getWaendeByHallenIdResponse400 = {
  data: void
  status: 400
}

export type getWaendeByHallenIdResponse404 = {
  data: void
  status: 404
}

export type getWaendeByHallenIdResponse500 = {
  data: void
  status: 500
}

export type getWaendeByHallenIdResponseSuccess = (getWaendeByHallenIdResponse200) & {
  headers: Headers;
};
export type getWaendeByHallenIdResponseError = (getWaendeByHallenIdResponse400 | getWaendeByHallenIdResponse404 | getWaendeByHallenIdResponse500) & {
  headers: Headers;
};

export type getWaendeByHallenIdResponse = (getWaendeByHallenIdResponseSuccess | getWaendeByHallenIdResponseError)

export const getGetWaendeByHallenIdUrl = (params: GetWaendeByHallenIdParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/waende?${stringifiedParams}` : `/api/waende`
}

export const getWaendeByHallenId = async (params: GetWaendeByHallenIdParams, options?: RequestInit): Promise<getWaendeByHallenIdResponse> => {
  
  const res = await fetch(getGetWaendeByHallenIdUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getWaendeByHallenIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getWaendeByHallenIdResponse
}
  




export const getGetWaendeByHallenIdQueryKey = (params?: GetWaendeByHallenIdParams,) => {
    return [
    `/api/waende`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetWaendeByHallenIdQueryOptions = <TData = Awaited<ReturnType<typeof getWaendeByHallenId>>, TError = void>(params: GetWaendeByHallenIdParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getWaendeByHallenId>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWaendeByHallenIdQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWaendeByHallenId>>> = ({ signal }) => getWaendeByHallenId(params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWaendeByHallenId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetWaendeByHallenIdQueryResult = NonNullable<Awaited<ReturnType<typeof getWaendeByHallenId>>>
export type GetWaendeByHallenIdQueryError = void



export function useGetWaendeByHallenId<TData = Awaited<ReturnType<typeof getWaendeByHallenId>>, TError = void>(
 params: GetWaendeByHallenIdParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getWaendeByHallenId>>, TError, TData>, fetch?: RequestInit}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetWaendeByHallenIdQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type addWandResponse201 = {
  data: Blob
  status: 201
}

export type addWandResponse400 = {
  data: void
  status: 400
}

export type addWandResponse404 = {
  data: void
  status: 404
}

export type addWandResponse500 = {
  data: void
  status: 500
}

export type addWandResponseSuccess = (addWandResponse201) & {
  headers: Headers;
};
export type addWandResponseError = (addWandResponse400 | addWandResponse404 | addWandResponse500) & {
  headers: Headers;
};

export type addWandResponse = (addWandResponseSuccess | addWandResponseError)

export const getAddWandUrl = () => {


  

  return `/api/waende`
}

export const addWand = async (wand: Wand, options?: RequestInit): Promise<addWandResponse> => {
  
  const res = await fetch(getAddWandUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      wand,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: addWandResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as addWandResponse
}
  



export const getAddWandMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addWand>>, TError,{data: Wand}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof addWand>>, TError,{data: Wand}, TContext> => {

const mutationKey = ['addWand'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addWand>>, {data: Wand}> = (props) => {
          const {data} = props ?? {};

          return  addWand(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AddWandMutationResult = NonNullable<Awaited<ReturnType<typeof addWand>>>
    export type AddWandMutationBody = Wand
    export type AddWandMutationError = void

    export const useAddWand = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addWand>>, TError,{data: Wand}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof addWand>>,
        TError,
        {data: Wand},
        TContext
      > => {
      return useMutation(getAddWandMutationOptions(options));
    }
    export type deleteWandResponse204 = {
  data: void
  status: 204
}

export type deleteWandResponse400 = {
  data: void
  status: 400
}

export type deleteWandResponse404 = {
  data: void
  status: 404
}

export type deleteWandResponse500 = {
  data: void
  status: 500
}

export type deleteWandResponseSuccess = (deleteWandResponse204) & {
  headers: Headers;
};
export type deleteWandResponseError = (deleteWandResponse400 | deleteWandResponse404 | deleteWandResponse500) & {
  headers: Headers;
};

export type deleteWandResponse = (deleteWandResponseSuccess | deleteWandResponseError)

export const getDeleteWandUrl = (params: DeleteWandParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/waende?${stringifiedParams}` : `/api/waende`
}

export const deleteWand = async (params: DeleteWandParams, options?: RequestInit): Promise<deleteWandResponse> => {
  
  const res = await fetch(getDeleteWandUrl(params),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteWandResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteWandResponse
}
  



export const getDeleteWandMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWand>>, TError,{params: DeleteWandParams}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteWand>>, TError,{params: DeleteWandParams}, TContext> => {

const mutationKey = ['deleteWand'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteWand>>, {params: DeleteWandParams}> = (props) => {
          const {params} = props ?? {};

          return  deleteWand(params,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteWandMutationResult = NonNullable<Awaited<ReturnType<typeof deleteWand>>>
    
    export type DeleteWandMutationError = void

    export const useDeleteWand = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWand>>, TError,{params: DeleteWandParams}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteWand>>,
        TError,
        {params: DeleteWandParams},
        TContext
      > => {
      return useMutation(getDeleteWandMutationOptions(options));
    }
    export type updateWandResponse200 = {
  data: Blob
  status: 200
}

export type updateWandResponse400 = {
  data: void
  status: 400
}

export type updateWandResponse404 = {
  data: void
  status: 404
}

export type updateWandResponse500 = {
  data: void
  status: 500
}

export type updateWandResponseSuccess = (updateWandResponse200) & {
  headers: Headers;
};
export type updateWandResponseError = (updateWandResponse400 | updateWandResponse404 | updateWandResponse500) & {
  headers: Headers;
};

export type updateWandResponse = (updateWandResponseSuccess | updateWandResponseError)

export const getUpdateWandUrl = () => {


  

  return `/api/waende`
}

export const updateWand = async (wand: Wand, options?: RequestInit): Promise<updateWandResponse> => {
  
  const res = await fetch(getUpdateWandUrl(),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      wand,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateWandResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateWandResponse
}
  



export const getUpdateWandMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateWand>>, TError,{data: Wand}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof updateWand>>, TError,{data: Wand}, TContext> => {

const mutationKey = ['updateWand'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateWand>>, {data: Wand}> = (props) => {
          const {data} = props ?? {};

          return  updateWand(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateWandMutationResult = NonNullable<Awaited<ReturnType<typeof updateWand>>>
    export type UpdateWandMutationBody = Wand
    export type UpdateWandMutationError = void

    export const useUpdateWand = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateWand>>, TError,{data: Wand}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateWand>>,
        TError,
        {data: Wand},
        TContext
      > => {
      return useMutation(getUpdateWandMutationOptions(options));
    }
    